
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRINGS = 54;
  public static final int SHORT = 28;
  public static final int CHARS = 55;
  public static final int MULT = 36;
  public static final int CONST = 13;
  public static final int CHAR = 25;
  public static final int EQUALS = 46;
  public static final int PLUS_ASSIGN = 39;
  public static final int NUMCONST = 53;
  public static final int MINUS_MINUS = 33;
  public static final int CASE = 15;
  public static final int GREATER = 51;
  public static final int LPAREN = 9;
  public static final int CONTINUE = 16;
  public static final int INT = 26;
  public static final int LESS = 52;
  public static final int MINUS = 35;
  public static final int FOR = 20;
  public static final int WRITE = 31;
  public static final int STATIC = 56;
  public static final int RPAREN = 10;
  public static final int NOT = 48;
  public static final int AND = 44;
  public static final int SEMICOLON = 3;
  public static final int OR = 45;
  public static final int COMMA = 6;
  public static final int DIV = 37;
  public static final int PLUS = 34;
  public static final int GREATER_EQUALS = 50;
  public static final int ASSIGN = 5;
  public static final int IF = 21;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int PLUS_PLUS = 32;
  public static final int DISTINCT = 47;
  public static final int error = 1;
  public static final int LCURLY = 11;
  public static final int MOD = 38;
  public static final int BREAK = 14;
  public static final int VOID = 29;
  public static final int MOD_ASSIGN = 43;
  public static final int DIV_ASSIGN = 42;
  public static final int SWITCH = 23;
  public static final int RCURLY = 12;
  public static final int LBRACK = 8;
  public static final int COLON = 4;
  public static final int ELSE = 19;
  public static final int LESS_EQUALS = 49;
  public static final int READ = 30;
  public static final int RBRACK = 7;
  public static final int WHILE = 24;
  public static final int DEFAULT = 17;
  public static final int LONG = 27;
  public static final int MULT_ASSIGN = 41;
  public static final int MINUS_ASSIGN = 40;
  public static final int DO = 18;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "SEMICOLON",
  "COLON",
  "ASSIGN",
  "COMMA",
  "RBRACK",
  "LBRACK",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "CONST",
  "BREAK",
  "CASE",
  "CONTINUE",
  "DEFAULT",
  "DO",
  "ELSE",
  "FOR",
  "IF",
  "RETURN",
  "SWITCH",
  "WHILE",
  "CHAR",
  "INT",
  "LONG",
  "SHORT",
  "VOID",
  "READ",
  "WRITE",
  "PLUS_PLUS",
  "MINUS_MINUS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "MULT_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "AND",
  "OR",
  "EQUALS",
  "DISTINCT",
  "NOT",
  "LESS_EQUALS",
  "GREATER_EQUALS",
  "GREATER",
  "LESS",
  "NUMCONST",
  "STRINGS",
  "CHARS",
  "STATIC"
  };
}

