
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INT = 9;
  public static final int LONG = 12;
  public static final int STATIC = 11;
  public static final int EOF = 0;
  public static final int ID = 3;
  public static final int RBRACK = 6;
  public static final int NUMCONST = 14;
  public static final int ASSIGN = 5;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int SEMICOLON = 2;
  public static final int LBRACK = 7;
  public static final int SHORT = 13;
  public static final int CHAR = 10;
  public static final int CONST = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "ID",
  "COMMA",
  "ASSIGN",
  "RBRACK",
  "LBRACK",
  "CONST",
  "INT",
  "CHAR",
  "STATIC",
  "LONG",
  "SHORT",
  "NUMCONST"
  };
}

